Repository stackrox/kernel-packer, pull requests merged in 2023-04, with the labels that each got.

#271 Manually add kernel from RHEL 9.2 Beta compose path used by OCP 4.13
  kernel-package-lists/rhel-uncrawled.txt
Labels: crawl

#275 Ensure PRs don't fail when not crawling
  .github/workflows/crawl.yml
Labels: lgtm

#274 Fix the regex used for searching make errors
  .github/workflows/main.yml
Labels: crawl, lgtm

#276 Downgrade missing kbuild error
  tools/generate-manifest/reformatters/reformatters.go
Labels: lgtm
